##############################################################################
#   JOINT KEY
##############################################################################
#   REQUIRED
#     name:           the joint name, must match urdf definition
#     bus:           the com bus number that the servo is attached to
#     servo:          the servo number for the joints
#     flip:           use value of [1] if your robot joint orientation is the same as the urdf model,
#                     or use value of [-1] if your robot joint orientation is the opposite of the urdf model
#                     each joint will tell you the urdf orientation of that joint
#   OPTIONAL
#     servopin:       the arduino pin the servo object is connected to
#     sensorpin:      (if available) the a/d input pin used for sensing position
#     minpulse:       the minimum pulse value allowed
#     maxpulse:       the maximum pulse value allowed
#     minangle:       the command angle associated with the minpulse value
#     maxangle:       the command angle associated with the maxpulse value
#     minsensor:      the sensorpin input when at the minpulse position
#     maxsensor:      the sensorpin input when at the maxpulse position
#     smoothing:      which smoothing strategy to use for motion?
#                       0 - direct drive, no smoothing, no maxspeed
#                       1 - direct drive, honor maxspeed value
#                       2 - trapezoidal accel/decel ramp, honor maxspeed value
#                       3 - cos accel/decel ramp, honor maxspeed value
#                       4 - cos^2 accel/decl ramp, honor maxspeed value
#     maxspeed:       the maxspeed allowed for motion?

bringup:
  angles:        degrees
  hz:            40

joints:

  l_shoulder_lift_joint:
    bus:          01
    servo:        09
    flip:          1
    servopin:     09
    sensorpin:    16
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1
    
  l_shoulder_out_joint:
    bus:          01
    servo:        08
    flip:          1
    servopin:     08
    sensorpin:    17
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  l_upper_arm_roll_joint:
    bus:          01
    servo:        07
    flip:          1
    servopin:     07
    sensorpin:    18
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  l_elbow_flex_joint:
    bus:          01
    servo:        06
    flip:          1
    servopin:     06
    sensorpin:    19
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  l_wrist_roll_joint:
    bus:          01
    servo:        05
    flip:          1
    servopin:     05
    sensorpin:    20
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  l_thumb_joint:
    bus:          01
    servo:        04
    flip:          1
    servopin:     04
    sensorpin:    21
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  l_index_joint:
    bus:          01
    servo:        03
    flip:          1
    servopin:     03
    sensorpin:    37
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  l_middle_joint:
    bus:          01
    servo:        02
    flip:          1
    servopin:     02
    sensorpin:    34
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  l_ring_joint:
    bus:          01
    servo:        01
    flip:          1
    servopin:     01
    sensorpin:    23
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  l_pinky_joint:
    bus:          01
    servo:        00
    flip:          1
    servopin:     00
    sensorpin:    22
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_shoulder_lift_joint:
    bus:          02
    servo:        09
    flip:          1
    servopin:     09
    sensorpin:    16
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1
    
  r_shoulder_out_joint:
    bus:          02
    servo:        08
    flip:          1
    servopin:     08
    sensorpin:    17
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_upper_arm_roll_joint:
    bus:          02
    servo:        07
    flip:          1
    servopin:     07
    sensorpin:    18
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_elbow_flex_joint:
    bus:          02
    servo:        06
    flip:          1
    servopin:     06
    sensorpin:    19
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_wrist_roll_joint:
    bus:          02
    servo:        05
    flip:          1
    servopin:     05
    sensorpin:    20
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_thumb_joint:
    bus:          02
    servo:        04
    flip:          1
    servopin:     04
    sensorpin:    21
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_index_joint:
    bus:          02
    servo:        03
    flip:          1
    servopin:     03
    sensorpin:    37
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_middle_joint:
    bus:          02
    servo:        02
    flip:          1
    servopin:     02
    sensorpin:    34
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_ring_joint:
    bus:          02
    servo:        01
    flip:          1
    servopin:     01
    sensorpin:    23
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  r_pinky_joint:
    bus:          02
    servo:        00
    flip:          1
    servopin:     00
    sensorpin:    22
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1
    
  waist_roll_joint:
    bus:          00
    servo:        07
    flip:          1
    servopin:     -1
    sensorpin:    -1
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  waist_tilt_joint:
    bus:          00
    servo:        06
    flip:          1
    servopin:     -1
    sensorpin:    -1
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  head_roll_joint:
    bus:          00
    servo:        05
    flip:          1
    servopin:     -1
    sensorpin:    -1
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  head_pan_joint:
    bus:          00
    servo:        03
    flip:          1
    servopin:     -1
    sensorpin:    -1
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  head_tilt_joint:
    bus:          00
    servo:        04
    flip:          1
    servopin:     -1
    sensorpin:    -1
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  jaw_joint:
    bus:          00
    servo:        02
    flip:          1
    servopin:     -1
    sensorpin:    -1
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  eyes_pan_joint:
    bus:          00
    servo:        00
    flip:          1
    servopin:     -1
    sensorpin:    -1
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

  eyes_tilt_joint:
    bus:          00
    servo:        01
    flip:          1
    servopin:     -1
    sensorpin:    -1
    minangle:     -1
    maxangle:     -1
    minpulse:     -1
    maxpulse:     -1
    minsensor:    -1
    maxsensor:    -1
    smoothing:    -1
    maxspeed:     -1

