##############################################################################
#   JOINT KEY
##############################################################################
#   REQUIRED
#     name:           the joint name, must match urdf definition
#     bus:           the com bus number that the servo is attached to
#     servo:          the servo number for the joints
#     flip:           use value of [1] if your robot joint orientation is the same as the urdf model,
#                     or use value of [-1] if your robot joint orientation is the opposite of the urdf model
#                     each joint will tell you the urdf orientation of that joint
#   OPTIONAL
#     servopin:       the arduino pin the servo object is connected to
#     sensorpin:      (if available) the a/d input pin used for sensing position
#     minpulse:       the minimum pulse value allowed
#     maxpulse:       the maximum pulse value allowed
#     minangle:       the command angle associated with the minpulse value
#     maxangle:       the command angle associated with the maxpulse value
#     minsensor:      the sensorpin input when at the minpulse position
#     maxsensor:      the sensorpin input when at the maxpulse position
#     smoothing:      which smoothing strategy to use for motion?
#                       0 - direct drive, no smoothing, no maxspeed
#                       1 - direct drive, honor maxspeed value
#                       2 - trapezoidal accel/decel ramp, honor maxspeed value
#                       3 - cos accel/decel ramp, honor maxspeed value
#                       4 - cos^2 accel/decl ramp, honor maxspeed value
#     maxspeed:       the maxspeed allowed for motion?

joints:

  angles:      degrees

  joint00:
    name:             l_shoulder_lift_joint
    bus:            00
    servo:          09
    flip:            f
    servopin:       09
    sensorpin:      16
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1
    
  joint01:
    name:             l_shoulder_out_joint
    bus:            00
    servo:          08
    flip:            f
    servopin:       08
    sensorpin:      17
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint02:
    name:             l_upper_arm_roll_joint
    bus:            00
    servo:          07
    flip:            f
    servopin:       07
    sensorpin:      18
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint03:
    name:             l_elbow_flex_joint
    bus:            00
    servo:          06
    flip:            f
    servopin:       06
    sensorpin:      19
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint04:
    name:             l_wrist_roll_joint
    bus:            00
    servo:          05
    flip:            f
    servopin:       05
    sensorpin:      20
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint05:
    name:             l_thumb_joint
    bus:            00
    servo:          04
    flip:            f
    servopin:       04
    sensorpin:      21
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint06:
    name:             l_index_joint
    bus:            00
    servo:          03
    flip:            f
    servopin:       03
    sensorpin:      37
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint07:
    name:             l_middle_joint
    bus:           00
    servo:          02
    flip:            f
    servopin:       02
    sensorpin:      34
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint08:
    name:             l_ring_joint
    bus:           00
    servo:          01
    flip:            f
    servopin:       01
    sensorpin:      23
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint09:
    name:             l_pinky_joint
    bus:           00
    servo:          00
    flip:            f
    servopin:       00
    sensorpin:      22
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint10:
    name:             r_shoulder_lift_joint
    bus:           01
    servo:          09
    flip:            f
    servopin:       09
    sensorpin:      16
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1
    
  joint11:
    name:             r_shoulder_out_joint
    bus:           01
    servo:          08
    flip:            f
    servopin:       08
    sensorpin:      17
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint12:
    name:             r_upper_arm_roll_joint
    bus:           01
    servo:          07
    flip:            f
    servopin:       07
    sensorpin:      18
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint13:
    name:             r_elbow_flex_joint
    bus:           01
    servo:          06
    flip:            f
    servopin:       06
    sensorpin:      19
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint14:
    name:             r_wrist_roll_joint
    bus:           01
    servo:          05
    flip:            f
    servopin:       05
    sensorpin:      20
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint15:
    name:             r_thumb_joint
    bus:           01
    servo:          04
    flip:            f
    servopin:       04
    sensorpin:      21
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint16:
    name:             r_index_joint
    bus:           01
    servo:          03
    flip:            f
    servopin:       03
    sensorpin:      37
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint17:
    name:             r_middle_joint
    bus:           01
    servo:          02
    flip:            f
    servopin:       02
    sensorpin:      34
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint18:
    name:             r_ring_joint
    bus:           01
    servo:          01
    flip:            f
    servopin:       01
    sensorpin:      23
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint19:
    name:             r_pinky_joint
    bus:           01
    servo:          00
    flip:            f
    servopin:       00
    sensorpin:      22
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1
    
  joint20:
    name:             waist_roll_joint
    bus:           02
    servo:          07
    flip:            f
    servopin:       -1
    sensorpin:      -1
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint21:
    name:             waist_tilt_joint
    bus:           02
    servo:          06
    flip:            f
    servopin:       -1
    sensorpin:      -1
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint22:
    name:             head_roll_joint
    bus:           02
    servo:          05
    flip:            f
    servopin:       -1
    sensorpin:      -1
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint23:
    name:             head_pitch_joint
    bus:           02
    servo:          04
    flip:            f
    servopin:       -1
    sensorpin:      -1
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint24:
    name:             head_yaw_joint
    bus:           02
    servo:          03
    flip:            f
    servopin:       -1
    sensorpin:      -1
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint25:
    name:             jaw_joint
    bus:           02
    servo:          02
    flip:            f
    servopin:       -1
    sensorpin:      -1
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint26:
    name:             eyes_pan_joint
    bus:           02
    servo:          01
    flip:            f
    servopin:       -1
    sensorpin:      -1
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

  joint27:
    name:             eyes_tilt_joint
    bus:           02
    servo:          00
    flip:            f
    servopin:       -1
    sensorpin:      -1
    minangle:       -1
    maxangle:       -1
    minpulse:       -1
    maxpulse:       -1
    minsensor:      -1
    maxsensor:      -1
    smoothing:      -1
    maxspeed:       -1

